import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const inter = Bebas_Neue({ subsets: ["latin"], weight: ["400"] });

const inter = Inter({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Maximize Earning With Wyld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full w-full bg-black">
          <div>
            <Navbar />
          </div>
          <div className="pt-16 bg-black">{children}</div>

          <div className="bg-black">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
